### ISSUE TITLE
Incorrect error message when bad seed phrase is used in recovery

### ISSUE THREAD

**Issue by privateidentity** [mwcproject/mwc-qt-wallet#435] opened 2020-06-25 14:13 UTC
When a user attempts to recover a wallet using a seed phrase and inputs a bad seed phrase a general error message is shown.

The issue appears to be related to when enabling tor the foreign api is also enabled.
There is logic that catches any time mwc713 errors out and displays that message.
The foreign API message is being incorrectly displayed instead of the appropriate seed recovery error message.

![seed phrase bug](https://user-images.githubusercontent.com/64110976/85735193-da828c00-b740-11ea-87a3-3b155ef6ccbd.jpg)

**Comment by bayk** [comment] 2020-06-26 21:40
qt wallet suppose to validate the seed phrase. Probably it is broken under the Windows.
Foreign API is needed for TOR now. Probably we can't deactivate it any more.

**Comment by bayk** [comment] 2020-08-30 02:15
QT wallet process error correctly. I was able to reproduce it under the windows. mwc713 crashed because of synthetic but technically correct phrase. 
Message about Foreign API is correct. If user had custom setting they will be resetted.  I can add a verification for default TOR setting and not print Foreign API message.

So the root problem is mwc713.

**Comment by bayk** [comment] 2020-09-01 03:51
Testing:
Try to recover with a phrase 

taxi       volcano    position   attend     call       glory      
taxi       volcano    position   attend     call       glory      
taxi       volcano    position   attend     call       glory      
taxi       volcano    position   attend     call       glory      

You should see the error related to the phrase. You should not see the error that mwc713 stop working

**Comment by vinayaga07** [comment] 2020-09-16 15:05
Tried to recover with the below  phrase and not observed the  error that mwc713 stop working.

taxi volcano position attend call glory
taxi volcano position attend call glory
taxi volcano position attend call glory
taxi volcano position attend call glory

![image](https://user-images.githubusercontent.com/63310656/93355820-19b20c00-f85c-11ea-915c-a39f2ea84622.png)

Hence closing this ticket.

**Closed by vinayaga07** 2020-09-16 15:05 UTC
