### ISSUE TITLE
user confused by confirms being a positive number and confirmed status is "NO"

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#335] opened 2020-05-17 13:36 UTC
This transaction was actually not confirmed, but user thought it was because it said confirms = 2421. Also, the user clicked on the inputs/outputs and saw an input and thought it was the output. I think we need to separate inputs vs. outputs in this window to be more clear.

![image](https://user-images.githubusercontent.com/7232183/82148362-8367ce00-9808-11ea-8cc5-6cdc965e4af9.png)

**Comment by bayk** [comment] 2020-06-13 22:38
@cgilliard ,  original issue related to confirmations. It is happens because it is confirmation for the input. So the data is correct. The issue is UX.
I am going by default select Output and add prefix to the commit that will say if it is input or output.   Showing separately inputs and outputs with data duplication will not help, dialog is already large.

**Comment by vinayaga07** [comment] 2020-06-16 17:13
@bayk In the transcation page, I could always see the "Output 1".


![image](https://user-images.githubusercontent.com/63310656/84805968-ad3c2c80-b022-11ea-9365-6ee3efa0b646.png)

**Comment by bayk** [comment] 2020-06-16 20:13
Yes, it is expected. 
You can switch to inputs or other outputs if they exist

**Comment by vinayaga07** [comment] 2020-08-18 17:10
Closing this ticket, as per the above comment.

**Closed by vinayaga07** 2020-08-18 17:10 UTC
