### ISSUE TITLE
QT wallet task scheduler issue

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#296] opened 2020-05-07 17:43 UTC
During start we get that

![image](https://user-images.githubusercontent.com/42393608/81326981-76501f80-904f-11ea-950a-0b953f852fa8.png)

Here is logs about that

07.05.2020 22:42:15.207 MWC713 Starting new process: '/private/var/folders/3v/8m50rv9j3k120b5v_2414wdw0000gr/T/AppTranslocation/AE38C2DE-3B13-492C-A54C-FC4E6E8BBA8D/d/mwc-qt-wallet.app/Contents/MacOS/mwc713' '--config' '/Users/vmoorthy/mwc-qt-wallet/wallet713v2.toml' '--disable-history'
07.05.2020 22:42:15.239 Mwc713EventManager Task Mwc713Task(name=Starting)  Starting...
07.05.2020 22:42:15.251 mwc713>> Welcome to wallet713 for MWC v3.1.4
07.05.2020 22:42:15.251 mwc713-Event> S_WELCOME [3.1.4]
07.05.2020 22:42:15.252 mwc713>> Unlock your existing wallet or type `init` to initiate a new one
07.05.2020 22:42:15.252 mwc713>> Use `help` to see available commands
07.05.2020 22:42:15.252 mwc713-Event> S_NEED2UNLOCK []
07.05.2020 22:42:15.252 mwc713>> ERROR: could not unlock wallet! are you using the correct passphrase?
07.05.2020 22:42:15.252 mwc713>> wallet713> <<+)mwc713(+>>
07.05.2020 22:42:15.252 mwc713-Event> S_PASSWORD_ERROR []
07.05.2020 22:42:15.252 mwc713-Event> S_GENERIC_ERROR [could not unlock wallet! are you using the correct passphrase?]
07.05.2020 22:42:15.252 mwc713-Event> S_ERROR [could not unlock wallet! are you using the correct passphrase?]
07.05.2020 22:42:15.252 mwc713-Event> S_READY []
07.05.2020 22:42:15.252 Mwc713EventManager Task Mwc713Task(name=Starting)  Executing
07.05.2020 22:42:15.252 Mwc713EventManager Task Mwc713Task(unlock)  Starting...
07.05.2020 22:42:15.252 mwc713<< CENSORED: unlock
07.05.2020 22:42:15.311 mwc713>> Your mwcmq address: xmhKbBhyQNugRVX7Hm1HyzHHiiu4a7WPGP2sDm5b73pvHFyVYC4N
07.05.2020 22:42:15.311 mwc713>> <<+)mwc713(+>>
07.05.2020 22:42:15.311 mwc713-Event> S_YOUR_MWC_ADDRESS [xmhKbBhyQNugRVX7Hm1HyzHHiiu4a7WPGP2sDm5b73pvHFyVYC4N]
07.05.2020 22:42:15.311 mwc713-Event> S_READY []
07.05.2020 22:42:15.311 MWC713 emit onMwcAddress with xmhKbBhyQNugRVX7Hm1HyzHHiiu4a7WPGP2sDm5b73pvHFyVYC4N
07.05.2020 22:42:15.311 Mwc713EventManager Task Mwc713Task(unlock)  Executing
07.05.2020 22:42:15.311 MWC713 emit onLoginResult with 1
07.05.2020 22:42:15.311 Notification INFO  Successfully logged into the wallet
07.05.2020 22:42:15.311 MWC713 emit onNewNotificationMessage with NotifMsg(level=info, message=Successfully logged into the wallet)
07.05.2020 22:42:15.311 Mwc713EventManager Task Mwc713Task(name=TaskSubmitFile, Input=getrootpublickey)  Starting...
07.05.2020 22:42:15.311 mwc713<< getrootpublickey
07.05.2020 22:42:15.312 Airdrop Requesting: https://seed2.mwc.mw:8443/v1/claimsAvailable
07.05.2020 22:42:15.312 HODL Requesting: https://seed2.mwc.mw:8443/v1/getHODLStatus
07.05.2020 22:42:15.379 mwc713>> CENSORED
07.05.2020 22:42:15.379 Event> CENSORED
07.05.2020 22:42:15.379 Event> CENSORED
07.05.2020 22:42:15.379 Event> CENSORED
07.05.2020 22:42:15.379 Mwc713EventManager Task Mwc713Task(name=TaskSubmitFile, Input=getrootpublickey)  Executing
07.05.2020 22:42:15.379 MWC713 emit onRootPublicKey with rootPubKey=XXXXX message= signature=
07.05.2020 22:42:15.379 Mwc713EventManager Task Mwc713Task(name=TaskListeningStart, Input=listen -s)  Starting...
07.05.2020 22:42:15.379 mwc713<< listen -s
07.05.2020 22:42:15.380 mwc713>> starting mwcmqs listener...
07.05.2020 22:42:15.380 mwc713-Event> S_LISTENER_MQ_STARTING []
07.05.2020 22:42:15.412 mwc713>> <<+)mwc713(+>>
07.05.2020 22:42:15.412 mwc713-Event> S_READY []
07.05.2020 22:42:15.412 Mwc713EventManager Task Mwc713Task(name=TaskListeningStart, Input=listen -s)  Executing
07.05.2020 22:42:15.412 MWC713 emit onListeningStartResults with mqTry=1 kbTry=0 errorMessages size 0 initStart=True
07.05.2020 22:42:15.412 Mwc713EventManager Task Mwc713Task(name=TaskListeningStart, Input=listen -k)  Starting...
07.05.2020 22:42:15.412 mwc713<< listen -k
07.05.2020 22:42:15.413 mwc713>> starting keybase listener...
07.05.2020 22:42:15.413 mwc713>> wallet713> 
07.05.2020 22:42:15.413 mwc713-Event> S_LISTENER_KB_STARTING []
07.05.2020 22:42:15.415 mwc713>> Error: keybase not found! consider installing keybase locally first.
07.05.2020 22:42:15.415 mwc713>> wallet713> <<+)mwc713(+>>
07.05.2020 22:42:15.415 mwc713-Event> S_ERROR [keybase not found! consider installing keybase locally first.]
07.05.2020 22:42:15.415 mwc713-Event> S_READY []
07.05.2020 22:42:15.415 Notification CRITICAL  keybase not found! consider installing keybase locally first.
07.05.2020 22:42:15.415 MWC713 emit onNewNotificationMessage with NotifMsg(level=info, message=keybase not found! consider installing keybase locally first.)
07.05.2020 22:42:15.415 Mwc713EventManager Task Mwc713Task(name=TaskListeningStart, Input=listen -k)  Executing
07.05.2020 22:42:15.415 MWC713 emit onListeningStartResults with mqTry=0 kbTry=1 errorMessages size 1 initStart=True
07.05.2020 22:42:15.415 Mwc713EventManager Task Mwc713Task(set-recv for default)  Starting...
07.05.2020 22:42:15.415 mwc713<< CENSORED: set-recv for default
07.05.2020 22:42:15.416 mwc713>> Incoming funds will be received in account: "default"
07.05.2020 22:42:15.416 mwc713>> wallet713> <<+)mwc713(+>>
07.05.2020 22:42:15.416 mwc713-Event> S_SET_RECEIVE [default]
07.05.2020 22:42:15.416 mwc713-Event> S_READY []
07.05.2020 22:42:15.416 Mwc713EventManager Task Mwc713Task(set-recv for default)  Executing
07.05.2020 22:42:15.416 Notification INFO  Set receive account: 'default'
07.05.2020 22:42:15.416 MWC713 emit onNewNotificationMessage with NotifMsg(level=info, message=Set receive account: 'default')
07.05.2020 22:42:15.416 MWC713 emit onSetReceiveAccount with ok=1
07.05.2020 22:42:15.416 Mwc713EventManager Task Mwc713Task(name=TaskSync, Input=sync)  Starting...
07.05.2020 22:42:15.416 mwc713<< sync
07.05.2020 22:42:16.413 HODL Success respond for Tag: hodl_getHODLStatus  Reply {"success": true, "message": "Happy HODLing now!"}
07.05.2020 22:42:16.413 HODL emit onHodlStatusWasChanged with setHodlStatus
07.05.2020 22:42:16.485 Airdrop Fail respond for Tag: airdrop_claimsAvailable  requestErrorMessage: Error transferring https://seed2.mwc.mw:8443/v1/claimsAvailable - server replied: Not Found
07.05.2020 22:42:17.788 mwc713>> mwcmqs listener started for [xmhKbBhyQNugRVX7Hm1HyzHHiiu4a7WPGP2sDm5b73pvHFyVYC4N] tid=[YfnBhNWzVM5BprscTTJkO]
07.05.2020 22:42:17.788 mwc713-Event> S_LISTENER_ON [xmhKbBhyQNugRVX7Hm1HyzHHiiu4a7WPGP2sDm5b73pvHFyVYC4N|YfnBhNWzVM5BprscTTJkO]
07.05.2020 22:42:17.788 Notification INFO  Start listening on mwc mqs
07.05.2020 22:42:17.788 MWC713 emit onNewNotificationMessage with NotifMsg(level=info, message=Start listening on mwc mqs)
07.05.2020 22:42:17.788 MWC713 emit onMwcMqListenerStatus with online=1
07.05.2020 22:42:17.788 MWC713 emit onMwcAddress with xmhKbBhyQNugRVX7Hm1HyzHHiiu4a7WPGP2sDm5b73pvHFyVYC4N
07.05.2020 22:42:20.884 mwc713>> wallet713> 
07.05.2020 22:42:20.884 mwc713>> Your wallet data successfully synchronized with a node
07.05.2020 22:42:20.884 mwc713>> wallet713> <<+)mwc713(+>>
07.05.2020 22:42:20.884 mwc713-Event> S_READY []
07.05.2020 22:42:20.884 Mwc713EventManager Task Mwc713Task(name=TaskSync, Input=sync)  Executing
07.05.2020 22:42:20.884 Mwc713EventManager Task Mwc713Task(name=TaskAccountList, Input=accounts)  Starting...
07.05.2020 22:42:20.884 mwc713<< accounts
07.05.2020 22:42:20.885 mwc713>> ____ Wallet Accounts ____
07.05.2020 22:42:20.885 mwc713>>  Name    | Parent BIP-32 Derivation Path 
07.05.2020 22:42:20.885 mwc713>> ---------+-------------------------------
07.05.2020 22:42:20.885 mwc713>>  default | m/0/0 
07.05.2020 22:42:20.885 mwc713>> <<+)mwc713(+>>
07.05.2020 22:42:20.885 mwc713-Event> S_READY []
07.05.2020 22:42:20.885 Mwc713EventManager Task Mwc713Task(name=TaskAccountList, Input=accounts)  Executing
07.05.2020 22:42:20.885 Mwc713EventManager Task Mwc713Task(name=TaskNodeInfo, Input=nodeinfo)  Starting...
07.05.2020 22:42:20.885 mwc713<< nodeinfo
07.05.2020 22:42:23.735 mwc713>> Node Info:
07.05.2020 22:42:23.735 mwc713>> wallet713> 
07.05.2020 22:42:23.735 mwc713>> Height: 379400
07.05.2020 22:42:23.735 mwc713>> wallet713> 
07.05.2020 22:42:23.735 mwc713>> Total_Difficulty: 75176334411
07.05.2020 22:42:23.735 mwc713>> wallet713> 
07.05.2020 22:42:23.735 mwc713>> PeerInfo: [PeerInfoDisplay { capabilities: HEADER_HIST | TXHASHSET_HIST | PEER_LIST | TX_KERNEL_HASH | FULL_NODE, user_agent: "MW/MWC 4.0.0-beta.2", version: ProtocolVersion(2), addr: PeerAddr(V4(18.234.103.244:13414)), direction: Inbound, total_difficulty: Difficulty { num: 75176334411 }, height: 379400 }, PeerInfoDisplay { capabilities: HEADER_HIST | TXHASHSET_HIST | PEER_LIST | TX_KERNEL_HASH | FULL_NODE, user_agent: "MW/MWC 4.0.0-beta.1", version: ProtocolVersion(2), addr: PeerAddr(V4(73.158.42.120:13414)), direction: Inbound, total_difficulty: Difficulty { num: 75176334411 }, height: 379400 }, PeerInfoDisplay { capabilities: HEADER_HIST | TXHASHSET_HIST | PEER_LIST | TX_KERNEL_HASH | FULL_NODE, user_agent: "MW/MWC 3.1.4", version: ProtocolVersion(2), addr: PeerAddr(V4(54.166.67.123:13414)), direction: Inbound, total_difficulty: Difficulty { num: 75176334411 }, height: 379400 }, PeerInfoDisplay { capabilities: HEADER_HIST | TXHASHSET_HIST | PEER_LIST | TX_KERNEL_HASH | FULL_NODE, user_agent: "MW/MWC 3.1.1", version: ProtocolVersion(2), addr: PeerAddr(V4(162.207.46.237:13414)), direction: Inbound, total_difficulty: Difficulty { num: 75176334411 }, height: 379400 }, PeerInfoDisplay { capabilities: HEADER_HIST | TXHASHSET_HIST | PEER_LIST | TX_KERNEL_HASH | FULL_NODE, user_agent: "MW/MWC 4.0.0-beta.2", version: ProtocolVersion(2), addr: PeerAddr(V4(44.230.125.14:13414)), direction: Outbound, total_difficulty: Difficulty { num: 75176334411 }, height: 379400 }, PeerInfoDisplay { capabilities: HEADER_HIST | TXHASHSET_HIST | PEER_LIST | TX_KERNEL_HASH | FULL_NODE, user_agent: "MW/MWC 3.1.4", version: ProtocolVersion(2), addr: PeerAddr(V4(52.207.212.159:13414)), direction: Inbound, total_difficulty: Difficulty { num: 75176318453 }, height: 379325 }, PeerInfoDisplay { capabilities: HEADER_HIST | TXHASHSET_HIST | PEER_LIST | TX_KERNEL_HASH | FULL_NODE, user_agent: "MW/MWC 3.1.1", version: ProtocolVersion(2), addr: PeerAddr(V4(142.167.170.222:3414)), direction: Outbound, total_difficulty: Difficulty { num: 75176334411 }, height: 379400 }, PeerInfoDisplay { capabilities: HEADER_HIST | TXHASHSET_HIST | PEER_LIST | TX_KERNEL_HASH | FULL_NODE, user_agent: "MW/MWC 3.0.0", version: ProtocolVersion(2), addr: PeerAddr(V4(188.239.199.52:13414)), direction: Outbound, total_difficulty: Difficulty { num: 75176334411 }, height: 379400 }, PeerInfoDisplay { capabilities: HEADER_HIST | TXHASHSET_HIST | PEER_LIST | TX_KERNEL_HASH | FULL_NODE, user_agent: "MW/MWC 3.0.0", version: ProtocolVersion(2), addr: PeerAddr(V4(188.239.199.51:13414)), direction: Outbound, total_difficulty: Difficulty { num: 75176334411 }, height: 379400 }, PeerInfoDisplay { capabilities: HEADER_HIST | TXHASHSET_HIST | PEER_LIST | TX_KERNEL_HASH | FULL_NODE, user_agent: "MW/MWC 3.1.4", version: ProtocolVersion(2), addr: PeerAddr(V4(34.220.130.230:13414)), direction: Inbound, total_difficulty: Difficulty { num: 75176334411 }, height: 379400 }]
07.05.2020 22:42:23.735 mwc713>> wallet713> <<+)mwc713(+>>
07.05.2020 22:42:23.738 mwc713-Event> S_READY []
07.05.2020 22:42:23.738 Mwc713EventManager Task Mwc713Task(name=TaskNodeInfo, Input=nodeinfo)  Executing
07.05.2020 22:42:23.738 MWC713 emit setNodeStatus with online=1 NodeHeight=379400 PeerHeight=379400 totalDifficulty=75176334411 connections=10
07.05.2020 22:42:23.738 Mwc713EventManager Task Mwc713Task(name=TaskSubmitFile, Input=getrootpublickey)  Starting...
07.05.2020 22:42:23.738 mwc713<< getrootpublickey
07.05.2020 22:42:23.756 mwc713>> CENSORED
07.05.2020 22:42:23.756 Event> CENSORED
07.05.2020 22:42:23.756 Event> CENSORED
07.05.2020 22:42:23.756 Event> CENSORED
07.05.2020 22:42:23.756 Mwc713EventManager Task Mwc713Task(name=TaskSubmitFile, Input=getrootpublickey)  Executing
07.05.2020 22:42:23.756 MWC713 emit onRootPublicKey with rootPubKey=XXXXX message= signature=
07.05.2020 22:42:23.756 Mwc713EventManager Task Mwc713Task(account switch default)  Starting...
07.05.2020 22:42:23.756 mwc713<< CENSORED: account switch default
07.05.2020 22:42:23.756 HODL Requesting: https://seed2.mwc.mw:8443/v1/checkOutputs
07.05.2020 22:42:23.757 HODL Requesting: https://seed2.mwc.mw:8443/v1/getPendingHODLRewards
07.05.2020 22:42:23.781 mwc713>> <<+)mwc713(+>>
07.05.2020 22:42:23.781 mwc713-Event> S_READY []
07.05.2020 22:42:23.781 Mwc713EventManager Task Mwc713Task(account switch default)  Executing
07.05.2020 22:42:23.781 MWC713 emit onAccountSwitched with default
07.05.2020 22:42:23.781 Mwc713EventManager Task Mwc713Task(name=TaskAccountInfo, Input=info -c 10 --no-refresh)  Starting...
07.05.2020 22:42:23.782 mwc713<< info -c 10 --no-refresh
07.05.2020 22:42:23.883 mwc713>> ____ Wallet Summary Info - Account 'default' as of height 379400 ____
07.05.2020 22:42:23.883 mwc713-Event> S_ACCOUNTS_INFO_SUM [default|379400]
07.05.2020 22:42:23.883 mwc713>>  Confirmed Total                  | 5.000000000 
07.05.2020 22:42:23.883 mwc713>>  Awaiting Confirmation (< 10)     | 0.000000000 
07.05.2020 22:42:23.883 mwc713>>  Awaiting Finalization            | 3.300000000 
07.05.2020 22:42:23.883 mwc713>>  Locked by previous transaction   | 0.000000000 
07.05.2020 22:42:23.883 mwc713>>  -------------------------------- | ------------- 
07.05.2020 22:42:23.883 mwc713>>  Currently Spendable              | 5.000000000 
07.05.2020 22:42:23.883 mwc713>> <<+)mwc713(+>>
07.05.2020 22:42:23.884 mwc713-Event> S_READY []
07.05.2020 22:42:23.884 Mwc713EventManager Task Mwc713Task(name=TaskAccountInfo, Input=info -c 10 --no-refresh)  Executing
07.05.2020 22:42:23.884 Mwc713EventManager Task Mwc713Task(name=Outputs, Input=outputs --no-refresh)  Starting...
07.05.2020 22:42:23.884 mwc713<< outputs --no-refresh
07.05.2020 22:42:23.886 mwc713>> Wallet Outputs - Account 'default' - Block Height: 379400
07.05.2020 22:42:23.886 mwc713-Event> S_OUTPUT_LOG [default|379400]
07.05.2020 22:42:23.886 mwc713>> ----------------------------------------------------------------------------------------------------------------------------------------------------------------
07.05.2020 22:42:23.886 mwc713>>  Output Commitment                                                   MMR Index  Block Height  Locked Until  Status       Coinbase?  # Confirms  Value        Tx 
07.05.2020 22:42:23.886 mwc713>> ================================================================================================================================================================
07.05.2020 22:42:23.886 mwc713>>  084bba8c68f4999c81807f0d44eead5c2c182386a0be09fc0a1918ce736c172270  None       359220        0             Unspent      false      20181       5.000000000  0 
07.05.2020 22:42:23.886 mwc713>> ----------------------------------------------------------------------------------------------------------------------------------------------------------------
07.05.2020 22:42:23.886 mwc713>>  08130f7bda1dbc4cb4251c1e6c6d64fce15fbdffda426ae393ad7cd0627adc45be  None       358652        0             Unconfirmed  false      0           1.000000000  1 
07.05.2020 22:42:23.887 mwc713>> ----------------------------------------------------------------------------------------------------------------------------------------------------------------
07.05.2020 22:42:23.887 mwc713>>  09e35680976399e5cdbbaea7ab3a9f719a7f84911919db7ca511dbd9c393dca0b6  None       358667        0             Unconfirmed  false      0           1.200000000  2 
07.05.2020 22:42:23.887 mwc713>> ----------------------------------------------------------------------------------------------------------------------------------------------------------------
07.05.2020 22:42:23.887 mwc713>>  08d8bcc3332b676d66c69cbf724f60c2bae85193dca7bf2d9814b02aee256b78b2  None       358667        0             Unconfirmed  false      0           1.100000000  3 
07.05.2020 22:42:23.887 mwc713>> ----------------------------------------------------------------------------------------------------------------------------------------------------------------
07.05.2020 22:42:23.887 mwc713>> <<+)mwc713(+>>
07.05.2020 22:42:23.888 mwc713-Event> S_READY []
07.05.2020 22:42:23.888 Mwc713EventManager Task Mwc713Task(name=Outputs, Input=outputs --no-refresh)  Executing
07.05.2020 22:42:23.888 Mwc713EventManager Task Mwc713Task(name=TaskAccountProgress)  Starting...
07.05.2020 22:42:23.888 Mwc713EventManager Task Mwc713Task(name=TaskAccountProgress)  Executing
07.05.2020 22:42:23.888 MWC713 emit onWalletBalanceProgress with accountIdx=0 totalAccounts=1
07.05.2020 22:42:23.888 Mwc713EventManager Task Mwc713Task(name=TaskAccountListFinal)  Starting...
07.05.2020 22:42:23.888 Mwc713EventManager Task Mwc713Task(name=TaskAccountListFinal)  Executing
07.05.2020 22:42:23.888 HODL emit onHodlStatusWasChanged with setWalletOutputs
07.05.2020 22:42:23.888 MWC713 emit onWalletBalanceUpdated with origin from updateAccountFinalize, AccountInfo(acc=default, total=8.3 spend=5 locked=0 awaiting=3.3);
07.05.2020 22:42:23.888 Mwc713EventManager Task Mwc713Task(account switch default)  Starting...
07.05.2020 22:42:23.888 mwc713<< CENSORED: account switch default
07.05.2020 22:42:24.073 mwc713>> <<+)mwc713(+>>
07.05.2020 22:42:24.073 mwc713-Event> S_READY []
07.05.2020 22:42:24.073 Mwc713EventManager Task Mwc713Task(account switch default)  Executing
07.05.2020 22:42:24.073 MWC713 emit onAccountSwitched with default
07.05.2020 22:42:24.244 HODL Success respond for Tag: hodl_checkOutputs  Reply {"success":true,"outputs_qualified":[{"amount":"5.000000000000","commit":"084bba8c68f4999c81807f0d44eead5c2c182386a0be09fc0a1918ce736c172270","weight":0.9,"class":"Class 2"}]}
07.05.2020 22:42:24.244 HODL emit onHodlStatusWasChanged with setHodlOutputs
07.05.2020 22:42:24.767 HODL Success respond for Tag: hodl_getPendingHODLRewards  Reply {"success":true,"payments":[{"amount":"1000000000","claim_id":1,"status":3},{"amount":"1100000000","claim_id":2,"status":3},{"amount":"1200000000","claim_id":3,"status":3}]}
07.05.2020 22:42:24.767 HODL emit onHodlStatusWasChanged with setHodlClaimStatus
07.05.2020 22:42:38.192 Notification FATAL ERROR  mwc713 unable to process the task 'Starting'

**Comment by bayk** [comment] 2020-05-07 17:44
Will add more messages into the logs

**Comment by bayk** [comment] 2020-05-18 04:01
Please note, code change adding more logs, but root cause still not found.

**Comment by vinayaga07** [comment] 2020-05-18 17:29
Today with the latest build tried multiple times, but unable to reproduce the issue.
Will update this ticket, once I reproduced the issue.

**Comment by bayk** [comment] 2020-05-18 17:34
When you reproduce it, please upload the logs from qt wallet

**Comment by vinayaga07** [comment] 2020-05-27 17:41
Unable to reproduce the issue in the last 10 days of testing. Will raise a new ticket, if I got the issue in future. Hence closing this ticket.

**Closed by vinayaga07** 2020-05-27 17:41 UTC
Labels: bug
