### ISSUE TITLE
Notifications windows break Modal Dialogs functionality under the Windows.

### ISSUE THREAD

**Issue by bayk** [mwcproject/mwc-qt-wallet#613] opened 2020-11-20 02:12 UTC
Under the Windows modal dialogs and not the top most windows. As a result user doesn't see the modal, or modal doesn't show up, but all UI is frozen. 

Transaction below disable Notification functionality under the Windows. Please check to unable it when issue will be fixed.

**Comment by bayk** [comment] 2020-11-20 02:15
Sharon, please take a look. Since functionality disabled, It is not a release blocker. To enable it revert the commit above

**Comment by scasaletto** [comment] 2020-11-28 18:03
This issue has been fixed. To duplicate the issue, you need to use a nightly build prior to November 19th when Konstantin turned off notifications for Windows. So with an earlier nightly build, ensure notifications are turned on.  Then you need to get a main screen modal to occur. One way to cause a modal which demonstrates the issue is to start a second instance of the same wallet on another machine. So start Qt Wallet on your Windows machine and then start Qt Wallet, using the same wallet instance, on another machine. On the Windows machine a model should appear on screen warning that a second wallet instance has been started. But on Windows that modal is not displayed on screen but can only be seen if you click on the MWC Qt Wallet icon in the task bar. Once you click on the model in the task bar, the model will appear on screen and you can continue to use Qt Wallet. Otherwise it will appear as if Qt Wallet is unresponsive as the modal is waiting for you to click OK on it.
With the fix, the model will appear on screen as it should.

**Comment by vinayaga07** [comment] 2020-12-08 17:39
Verified, hence closing this ticket.

**Closed by vinayaga07** 2020-12-08 17:39 UTC
