### ISSUE TITLE
User on MacOSX reporting that drop down menus close immidiately

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#380] opened 2020-06-07 12:24 UTC
Every time any of the drop down menu selectors like in the transaction tab is selected, it immediately closes. He can only select by holding down the mouse button.

**Comment by bayk** [comment] 2020-06-10 23:31
I can't reproduce it. @jbyrer ,  can you try it.
I think if we can't reproduce, let's close it. That might be qt bug and there is not much what we can do.

**Closed** 2020-10-19 21:44 UTC
