### ISSUE TITLE
Changing any configuration settings in wallet config results in http listener being turned off

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#382] opened 2020-06-08 15:55 UTC
If your http listener is running and you make any changes to configuration (like number of confirmations), your http listener will be off on restart.

**Comment by bayk** [comment] 2020-06-12 21:54
Can't reproduce it now. Probably already fixed in current build.

**Comment by jbyrer** [comment] 2020-07-06 21:05
I can't reproduce it either, therefor closing.

**Closed** 2020-07-06 21:05 UTC
