### ISSUE TITLE
Transaction did not show up in receiver wallet, although success message was shown to user

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#236] opened 2020-04-04 22:43 UTC
This happened to Jim in testing.
1.) Send MWC from wallet a -> wallet b (wallet b is receiving to an account).
2.) Transaction succeeds and shows as confirmed in wallet a.
3.) Transaction found in block explorer.
4.) Transaction not shown in outputs or transaction tab for wallet b.
5.) Wallet b -> attempt to resync with full node. Transaction shows as "Received, Cancelled", balance is incorrect. It's missing the amount of this transaction in total balance.
6.) Recover wallet b from mnemonic fixes the issue. Correct balance shown and output found in output tab with recovered transaction for this amount.

No funds lost, but transaction history is lost in this case. Other reports of this from users. Seems to only happen when sending to an account. It doesn't happen all the time though.

**Comment by jbyrer** [comment] 2020-04-04 23:54
looks correct

**Comment by bayk** [comment] 2020-04-06 18:08
@jbyrer , we need to reproduce it. When you see that, please backup both of your wallets and share them.
Also, that can be possible because of large slate data corruption.

**Comment by bayk** [comment] 2020-04-06 18:08
Jim, I assign that to you to reproduce

**Comment by bayk** [comment] 2020-04-09 03:46
Jim, I think that was a related to what we push yesterday. All that accounts stuff, incorrect task optimization.  I am closing  it as a duplicate.

**Closed by bayk** 2020-04-09 03:46 UTC
