### ISSUE TITLE
user's need to understand that mwc-qt-wallet only listens to one address at a time.

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#151] opened 2019-12-04 22:45 UTC
Some users didn't understand this and did not receive withdrawals from the exchange because they specified an earlier address. Maybe @condensed-io can help with usability to determine how to make this clear without annoying the user.

**Comment by airdropmario** [comment] 2019-12-05 14:40
We made a Hotbit Withdrawal guide:

https://github.com/mwcproject/mwc-qt-wallet/blob/master/DOC/hotbit_withdrawal.md

It would probably be good to add this to the Reading section in the Footer on mwc.mw; perhaps in the Resources a section also.

In the mwc-qt-wallet it would be good to add warnings about Listening and perhaps reference the Guide (or a guide specifically on Listening that does not reference Hotbit) on the Receive tab and the MWC MQS tab. That way users at least get informed on this behavior that is unusual from most other crypto-assets.

Then Listening for multiple addresses can be rolled out in future versions.

**Comment by bayk** [comment] 2019-12-05 15:56
Hi  @condensed-io,  please share if you have any ideas about that. I really have no thoughts how to improve it. Single address is natural and to changes it action is required.

**Comment by condensed-io** [comment] 2019-12-10 09:06
@airdropmario thanks for the guide, I added an 'exchange' section to the footer with the link to Hotbit and the guide.  When we get more exchanges I'll pluralize it and list others there.  We'll probably be making an exchanges page soon on-site to house this content as well

**Comment by condensed-io** [comment] 2019-12-10 09:09
@cgilliard regarding the first question, let's discuss on Friday, I don't totally understand the problem.

**Comment by bayk** [comment] 2020-04-22 03:24
Duplicate of https://github.com/mwcproject/mwc-qt-wallet/issues/177

**Comment by vinayaga07** [comment] 2020-04-29 17:08
Duplicate, hence closing it.

**Closed by vinayaga07** 2020-04-29 17:08 UTC
Labels: duplicate
