### ISSUE TITLE
Unicode symbols - setup issue

### ISSUE THREAD

**Issue by mkd888** [mwcproject/mwc-qt-wallet#758] opened 2021-02-17 15:26 UTC
![error mwc](https://user-images.githubusercontent.com/79090099/108225351-281e8f80-713c-11eb-9fcd-4d7713ac7268.png)
Users with characters such as á, ě, ö, etc. in their Windows username are unable to setup a wallet. These characters are common in many world languages so it would be cool to fix it. I don't think many people will be willing to create a new user account just to install and run a wallet.

**Comment by bayk** [comment] 2021-02-20 18:27
The problem is our binary that are build with Rust. Most of 3rd party library doesn't process unicode strings correctly. That is why it is not allowed.
We are not fixing them, it is a limitation of technology that we are using.
Closing as wont't fix

**Closed by bayk** 2021-02-20 18:27 UTC
