### ISSUE TITLE
Mobile Wallet - Unexpected value in the input/outputs commitment info

### ISSUE THREAD

**Issue by vek-kal** [mwcproject/mwc-qt-wallet#815] opened 2021-03-12 20:18 UTC
I had only 5.001 mwc in my wallet and (unrelated : it was a slatepack self spend) and it's appears that of one my inputs was an amount of 858 MWC in the self-spend transactions details. Which cannot be true.

![Screenshot_2021-03-12-17-06-31-962_mw mwc wallet](https://user-images.githubusercontent.com/80525364/110994004-09dd3580-8370-11eb-9def-bb12a7804019.jpg)

**Comment by bayk** [comment] 2021-03-15 16:04
@sarawut11   please take a look. If you can't reproduce it, probably not much what we can do. Also I will create a ticket for for the next version about logs upload. In such situations we want users to able to send logs to us.

**Comment by vinayaga07** [comment] 2021-03-22 17:02
Verified with the latest build and observed results are not matching, hence re-opening this ticket.

![image](https://user-images.githubusercontent.com/63310656/112028742-8507ce00-8b5e-11eb-87ce-c1b5873d066c.png)

**Comment by bayk** [comment] 2021-03-22 17:47
@vinayaga07 ,  please explain what is not matching?  The numbers looks reasonable for me.

**Comment by vinayaga07** [comment] 2021-03-23 15:23
@bayk , For Sent Transaction, "Debited" MWC amount is wrong.

**Comment by bayk** [comment] 2021-03-23 16:26
@vinayaga07 , it is not wrong. Amount = Debited - Credited
-0.009 = 0.482 - 0.491
0.491 - You spent
0.482 - you get back as a change

**Comment by Viv-dev-mwc** [comment] 2021-04-07 15:53
Closing as per the above comments.

**Closed by Viv-dev-mwc** 2021-04-07 15:53 UTC
