### ISSUE TITLE
[QT-Wallet] Swap--> Help page needs a description about the page.

### ISSUE THREAD

**Issue by vinayaga07** [mwcproject/mwc-qt-wallet#606] opened 2020-11-13 15:57 UTC
**Description:**
Swap--> Help page needs a description about the Swap page and fonts need to be aligned same like "Transactions"--> Help Page.

Please refer the below screenshot for more details.

![image](https://user-images.githubusercontent.com/63310656/99091951-8ea08880-25f6-11eb-8ae0-7bd93139492b.png)

**Comment by bayk** [comment] 2021-01-17 21:56
@vinayaga07   please check if it is enough for the help. Do you feel that we need put more explanations here. We are expecting users to watch videos and read docs from MrT.  We might say that here.

**Comment by vinayaga07** [comment] 2021-01-18 15:41
@bayk Expecting a short description of "Auto Swap".
Herewith given below the Help description for the "Transaction" page.

![image](https://user-images.githubusercontent.com/63310656/104935790-aff46b00-59d1-11eb-9feb-21db0f98f140.png)

**Comment by bayk** [comment] 2021-01-19 00:25
Duplicate of #607

**Closed by bayk** 2021-01-19 00:25 UTC
Labels: bug
