### ISSUE TITLE
Cancelling any transaction results in saying transaction "1" was cancelled.

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#391] opened 2020-06-11 18:39 UTC
Create a transaction and cancel. It will always say cancelled transaction "1" success.

See example below. This was #330:

<img width="639" alt="Screen Shot 2020-06-11 at 11 38 14 AM" src="https://user-images.githubusercontent.com/7232183/84426463-262d2580-abd8-11ea-8aae-b8e0bcf47987.png">

**Comment by scasaletto** [comment] 2020-06-13 18:20
This issue was caused by a mismatch in function signatures when the signal that the transaction was cancelled event came in. This has been fixed.

**Comment by vinayaga07** [comment] 2020-06-16 17:15
Verified with the latest build, hence closing this ticket.

![image](https://user-images.githubusercontent.com/63310656/84806219-f7bda900-b022-11ea-86f8-67f2a3e55a8e.png)

**Closed by vinayaga07** 2020-06-16 17:15 UTC
