### ISSUE TITLE
user claims long mwc-qt-wallet password made it so his airdrop claim failed

### ISSUE THREAD

**Issue by cgilliard** [mwcproject/mwc-qt-wallet#142] opened 2019-12-02 21:48 UTC
@cpgilliard I shortened the "aidrop account password" to 8 characters, that didn't work. Then I recreated my mwc wallet with a shorter password, now I can claim all my MWC (I also tested one with a 32 chars password). So my problem was caused by the length of the mwc-qt-wallet password. Thanks for your help!

**Comment by bayk** [comment] 2019-12-03 01:34
mwc713 password can't affect the claiming API. It is independent workflows. May be there are timing issues?

**Comment by cgilliard** [comment] 2019-12-03 05:19
Might be. Maybe the password was somehow cached until he logged in again
with his new password?

**Comment by bayk** [comment] 2019-12-03 05:37
There is no cache for password.  There is a chance that the wallet was
created for the wrong network. Accidentally you can create wallet for floo
and than try to claim.
That will be an issues that really hard to guess. Transaction just didn't
go through.

**Comment by rsnel** [comment] 2019-12-03 09:37
I also had this problem, and solved it in the same way.

It says: give password, but it didn't prompt me for it. I had already typed in the password when the application started.

Relevant portion of the redacted log:

    02.12.2019 TIME.676 Airdrop Requesting: https://wallet.mwc.mw/v1/getAmount?password=<PASSWORD>&btcaddress=<ADDRESS>
    02.12.2019 TIME.859 Airdrop Success respond for Tag: getAmount  Reply {"success": true, "amount": "<AMOUNT>"}
    02.12.2019 TIME.865 Mwc713EventManager Task Mwc713Task(name=Starting)  Starting...
    02.12.2019 TIME.871 mwc713>> Welcome to wallet713 for MWC v2.4.8    
    02.12.2019 TIME.872 mwc713-Event> S_WELCOME [2.4.8]
    02.12.2019 TIME.872 mwc713-Event> S_LINE [Welcome to wallet713 for MWC v2.4.8]
    02.12.2019 TIME.872 mwc713>> Unlock your existing wallet or type `init` to initiate a new one
    02.12.2019 TIME.872 mwc713>> Use `help` to see available commands
    02.12.2019 TIME.872 mwc713-Event> S_NEED2UNLOCK [] 
    02.12.2019 TIME.872 mwc713-Event> S_LINE [Unlock your existing wallet or type `init` to initiate a new one]
    02.12.2019 TIME.873 mwc713-Event> S_LINE [Use `help` to see available commands]
    02.12.2019 TIME.873 mwc713>> ERROR: error: could not unlock wallet! are you using the correct passphrase?
    02.12.2019 TIME.873 mwc713>> wallet713> <<+)mwc713(+>>
    02.12.2019 TIME.873 mwc713-Event> S_PASSWORD_ERROR []
    02.12.2019 TIME.873 mwc713-Event> S_GENERIC_ERROR [error: could not unlock wallet! are you using the correct passphrase?]
    02.12.2019 TIME.873 mwc713-Event> S_ERROR [could not unlock wallet! are you using the correct passphrase?]
    02.12.2019 TIME.873 mwc713-Event> S_LINE [ERROR: error: could not unlock wallet! are you using the correct passphrase?]
    02.12.2019 TIME.873 mwc713-Event> S_READY []
    02.12.2019 TIME.874 mwc713-Event> S_LINE [<<+)mwc713(+>>]
    02.12.2019 TIME.874 Mwc713EventManager Task Mwc713Task(name=Starting)  Executing
    02.12.2019 TIME.874 Mwc713EventManager Task Mwc713Task(init with password (unlock))  Starting...
    02.12.2019 TIME.874 mwc713<< CENSORED: init with password (unlock)
    02.12.2019 TIME.875 mwc713>> Wallet seed file exists: /home/user/mwc-qt-wallet/gui_wallet713_data/wallet.seed
    02.12.2019 TIME.875 mwc713>> wallet713> <<+)mwc713(+>>
    02.12.2019 TIME.876 mwc713-Event> S_LINE [Wallet seed file exists: /home/user/mwc-qt-wallet/gui_wallet713_data/wallet.seed]
    02.12.2019 TIME.876 mwc713-Event> S_READY []
    02.12.2019 TIME.876 mwc713-Event> S_LINE [<<+)mwc713(+>>]
    02.12.2019 TIME.876 Mwc713EventManager Task Mwc713Task(init with password (unlock))  Executing
    02.12.2019 TIME.981 Mwc713EventManager Task Mwc713Task(name=pressEnter, Input= )  Starting...
    02.12.2019 LATER.981 mwc713<<
    02.12.2019 LATER.999 mwc713<< exit

**Comment by bayk** [comment] 2019-12-03 15:30
Press ENTER when you have done so    - printed when new wallet is initialized. 
CENSORED: init with password (unlock) - printed when you open a wallet with existing seed.

**Comment by bayk** [comment] 2019-12-04 05:10
I believe it is duplicate of  https://github.com/mwcproject/mwc-qt-wallet/issues/143

**Closed by bayk** 2019-12-04 05:10 UTC
